/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocatorStats {
    #[serde(rename = "numDirectArenas", skip_serializing_if = "Option::is_none")]
    pub num_direct_arenas: Option<i32>,
    #[serde(rename = "numHeapArenas", skip_serializing_if = "Option::is_none")]
    pub num_heap_arenas: Option<i32>,
    #[serde(rename = "numThreadLocalCaches", skip_serializing_if = "Option::is_none")]
    pub num_thread_local_caches: Option<i32>,
    #[serde(rename = "normalCacheSize", skip_serializing_if = "Option::is_none")]
    pub normal_cache_size: Option<i32>,
    #[serde(rename = "smallCacheSize", skip_serializing_if = "Option::is_none")]
    pub small_cache_size: Option<i32>,
    #[serde(rename = "tinyCacheSize", skip_serializing_if = "Option::is_none")]
    pub tiny_cache_size: Option<i32>,
    #[serde(rename = "directArenas", skip_serializing_if = "Option::is_none")]
    pub direct_arenas: Option<Vec<crate::models::PoolArenaStats>>,
    #[serde(rename = "heapArenas", skip_serializing_if = "Option::is_none")]
    pub heap_arenas: Option<Vec<crate::models::PoolArenaStats>>,
}

impl AllocatorStats {
    pub fn new() -> AllocatorStats {
        AllocatorStats {
            num_direct_arenas: None,
            num_heap_arenas: None,
            num_thread_local_caches: None,
            normal_cache_size: None,
            small_cache_size: None,
            tiny_cache_size: None,
            direct_arenas: None,
            heap_arenas: None,
        }
    }
}


