/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct BookieInfo {
    #[serde(rename = "rack", skip_serializing_if = "Option::is_none")]
    pub rack: Option<String>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
}

impl BookieInfo {
    pub fn new() -> BookieInfo {
        BookieInfo {
            rack: None,
            hostname: None,
        }
    }
}


