/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BrokerNamespaceIsolationData : The namespace isolation data for a given broker


#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct BrokerNamespaceIsolationData {
    /// The broker name
    #[serde(rename = "brokerName", skip_serializing_if = "Option::is_none")]
    pub broker_name: Option<String>,
    /// The namespace-isolation policies attached to this broker
    #[serde(rename = "namespaceRegex", skip_serializing_if = "Option::is_none")]
    pub namespace_regex: Option<Vec<String>>,
}

impl BrokerNamespaceIsolationData {
    /// The namespace isolation data for a given broker
    pub fn new() -> BrokerNamespaceIsolationData {
        BrokerNamespaceIsolationData {
            broker_name: None,
            namespace_regex: None,
        }
    }
}


