/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct CursorDetails {
    #[serde(rename = "cursorBacklog", skip_serializing_if = "Option::is_none")]
    pub cursor_backlog: Option<i64>,
    #[serde(rename = "cursorLedgerId", skip_serializing_if = "Option::is_none")]
    pub cursor_ledger_id: Option<i64>,
}

impl CursorDetails {
    pub fn new() -> CursorDetails {
        CursorDetails {
            cursor_backlog: None,
            cursor_ledger_id: None,
        }
    }
}


