/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct DispatchRate {
    #[serde(rename = "dispatchThrottlingRateInMsg", skip_serializing_if = "Option::is_none")]
    pub dispatch_throttling_rate_in_msg: Option<i32>,
    #[serde(rename = "dispatchThrottlingRateInByte", skip_serializing_if = "Option::is_none")]
    pub dispatch_throttling_rate_in_byte: Option<i64>,
    #[serde(rename = "ratePeriodInSecond", skip_serializing_if = "Option::is_none")]
    pub rate_period_in_second: Option<i32>,
}

impl DispatchRate {
    pub fn new() -> DispatchRate {
        DispatchRate {
            dispatch_throttling_rate_in_msg: None,
            dispatch_throttling_rate_in_byte: None,
            rate_period_in_second: None,
        }
    }
}


