/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FailureDomain : The data of a failure domain configuration in a cluster


#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct FailureDomain {
    /// The collection of brokers in the same failure domain
    #[serde(rename = "brokers", skip_serializing_if = "Option::is_none")]
    pub brokers: Option<Vec<String>>,
}

impl FailureDomain {
    /// The data of a failure domain configuration in a cluster
    pub fn new() -> FailureDomain {
        FailureDomain {
            brokers: None,
        }
    }
}


