/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct InternalConfigurationData {
    #[serde(rename = "zookeeperServers", skip_serializing_if = "Option::is_none")]
    pub zookeeper_servers: Option<String>,
    #[serde(rename = "configurationStoreServers", skip_serializing_if = "Option::is_none")]
    pub configuration_store_servers: Option<String>,
    #[serde(rename = "ledgersRootPath", skip_serializing_if = "Option::is_none")]
    pub ledgers_root_path: Option<String>,
    #[serde(rename = "stateStorageServiceUrl", skip_serializing_if = "Option::is_none")]
    pub state_storage_service_url: Option<String>,
}

impl InternalConfigurationData {
    pub fn new() -> InternalConfigurationData {
        InternalConfigurationData {
            zookeeper_servers: None,
            configuration_store_servers: None,
            ledgers_root_path: None,
            state_storage_service_url: None,
        }
    }
}


