/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LedgerDetails {
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<i64>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    #[serde(rename = "ledgerId", skip_serializing_if = "Option::is_none")]
    pub ledger_id: Option<i64>,
}

impl LedgerDetails {
    pub fn new() -> LedgerDetails {
        LedgerDetails {
            entries: None,
            timestamp: None,
            size: None,
            ledger_id: None,
        }
    }
}


