/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LedgerInfo {
    #[serde(rename = "ledgerId", skip_serializing_if = "Option::is_none")]
    pub ledger_id: Option<i64>,
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<i64>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    #[serde(rename = "offloaded", skip_serializing_if = "Option::is_none")]
    pub offloaded: Option<bool>,
}

impl LedgerInfo {
    pub fn new() -> LedgerInfo {
        LedgerInfo {
            ledger_id: None,
            entries: None,
            size: None,
            offloaded: None,
        }
    }
}


