/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageIdImpl {
    #[serde(rename = "ledgerId", skip_serializing_if = "Option::is_none")]
    pub ledger_id: Option<i64>,
    #[serde(rename = "entryId", skip_serializing_if = "Option::is_none")]
    pub entry_id: Option<i64>,
    #[serde(rename = "partitionIndex", skip_serializing_if = "Option::is_none")]
    pub partition_index: Option<i32>,
}

impl MessageIdImpl {
    pub fn new() -> MessageIdImpl {
        MessageIdImpl {
            ledger_id: None,
            entry_id: None,
            partition_index: None,
        }
    }
}


