/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct NamespaceOwnershipStatus {
    #[serde(rename = "broker_assignment", skip_serializing_if = "Option::is_none")]
    pub broker_assignment: Option<BrokerAssignment>,
    #[serde(rename = "is_controlled", skip_serializing_if = "Option::is_none")]
    pub is_controlled: Option<bool>,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl NamespaceOwnershipStatus {
    pub fn new() -> NamespaceOwnershipStatus {
        NamespaceOwnershipStatus {
            broker_assignment: None,
            is_controlled: None,
            is_active: None,
        }
    }
}

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum BrokerAssignment {
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "secondary")]
    Secondary,
    #[serde(rename = "shared")]
    Shared,
}

