/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct NonPersistentTopicStats {
    #[serde(rename = "msgRateIn", skip_serializing_if = "Option::is_none")]
    pub msg_rate_in: Option<f64>,
    #[serde(rename = "msgThroughputIn", skip_serializing_if = "Option::is_none")]
    pub msg_throughput_in: Option<f64>,
    #[serde(rename = "msgRateOut", skip_serializing_if = "Option::is_none")]
    pub msg_rate_out: Option<f64>,
    #[serde(rename = "msgThroughputOut", skip_serializing_if = "Option::is_none")]
    pub msg_throughput_out: Option<f64>,
    #[serde(rename = "averageMsgSize", skip_serializing_if = "Option::is_none")]
    pub average_msg_size: Option<f64>,
    #[serde(rename = "storageSize", skip_serializing_if = "Option::is_none")]
    pub storage_size: Option<i64>,
    #[serde(rename = "publishers", skip_serializing_if = "Option::is_none")]
    pub publishers: Option<Vec<crate::models::NonPersistentPublisherStats>>,
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<::std::collections::HashMap<String, crate::models::NonPersistentSubscriptionStats>>,
    #[serde(rename = "replication", skip_serializing_if = "Option::is_none")]
    pub replication: Option<::std::collections::HashMap<String, crate::models::NonPersistentReplicatorStats>>,
    #[serde(rename = "deduplicationStatus", skip_serializing_if = "Option::is_none")]
    pub deduplication_status: Option<String>,
    #[serde(rename = "msgDropRate", skip_serializing_if = "Option::is_none")]
    pub msg_drop_rate: Option<f64>,
}

impl NonPersistentTopicStats {
    pub fn new() -> NonPersistentTopicStats {
        NonPersistentTopicStats {
            msg_rate_in: None,
            msg_throughput_in: None,
            msg_rate_out: None,
            msg_throughput_out: None,
            average_msg_size: None,
            storage_size: None,
            publishers: None,
            subscriptions: None,
            replication: None,
            deduplication_status: None,
            msg_drop_rate: None,
        }
    }
}


