/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct PartitionedTopicMetadata {
    #[serde(rename = "partitions", skip_serializing_if = "Option::is_none")]
    pub partitions: Option<i32>,
}

impl PartitionedTopicMetadata {
    pub fn new() -> PartitionedTopicMetadata {
        PartitionedTopicMetadata {
            partitions: None,
        }
    }
}


