/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingBookieOpsStats {
    #[serde(rename = "dataLedgerOpenOp", skip_serializing_if = "Option::is_none")]
    pub data_ledger_open_op: Option<i64>,
    #[serde(rename = "dataLedgerCloseOp", skip_serializing_if = "Option::is_none")]
    pub data_ledger_close_op: Option<i64>,
    #[serde(rename = "dataLedgerCreateOp", skip_serializing_if = "Option::is_none")]
    pub data_ledger_create_op: Option<i64>,
    #[serde(rename = "dataLedgerDeleteOp", skip_serializing_if = "Option::is_none")]
    pub data_ledger_delete_op: Option<i64>,
    #[serde(rename = "cursorLedgerOpenOp", skip_serializing_if = "Option::is_none")]
    pub cursor_ledger_open_op: Option<i64>,
    #[serde(rename = "cursorLedgerCloseOp", skip_serializing_if = "Option::is_none")]
    pub cursor_ledger_close_op: Option<i64>,
    #[serde(rename = "cursorLedgerCreateOp", skip_serializing_if = "Option::is_none")]
    pub cursor_ledger_create_op: Option<i64>,
    #[serde(rename = "cursorLedgerDeleteOp", skip_serializing_if = "Option::is_none")]
    pub cursor_ledger_delete_op: Option<i64>,
}

impl PendingBookieOpsStats {
    pub fn new() -> PendingBookieOpsStats {
        PendingBookieOpsStats {
            data_ledger_open_op: None,
            data_ledger_close_op: None,
            data_ledger_create_op: None,
            data_ledger_delete_op: None,
            cursor_ledger_open_op: None,
            cursor_ledger_close_op: None,
            cursor_ledger_create_op: None,
            cursor_ledger_delete_op: None,
        }
    }
}


