/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct PersistentOfflineTopicStats {
    #[serde(rename = "storageSize", skip_serializing_if = "Option::is_none")]
    pub storage_size: Option<i64>,
    #[serde(rename = "totalMessages", skip_serializing_if = "Option::is_none")]
    pub total_messages: Option<i64>,
    #[serde(rename = "messageBacklog", skip_serializing_if = "Option::is_none")]
    pub message_backlog: Option<i64>,
    #[serde(rename = "brokerName", skip_serializing_if = "Option::is_none")]
    pub broker_name: Option<String>,
    #[serde(rename = "topicName", skip_serializing_if = "Option::is_none")]
    pub topic_name: Option<String>,
    #[serde(rename = "dataLedgerDetails", skip_serializing_if = "Option::is_none")]
    pub data_ledger_details: Option<Vec<crate::models::LedgerDetails>>,
    #[serde(rename = "cursorDetails", skip_serializing_if = "Option::is_none")]
    pub cursor_details: Option<::std::collections::HashMap<String, crate::models::CursorDetails>>,
    #[serde(rename = "statGeneratedAt", skip_serializing_if = "Option::is_none")]
    pub stat_generated_at: Option<String>,
}

impl PersistentOfflineTopicStats {
    pub fn new() -> PersistentOfflineTopicStats {
        PersistentOfflineTopicStats {
            storage_size: None,
            total_messages: None,
            message_backlog: None,
            broker_name: None,
            topic_name: None,
            data_ledger_details: None,
            cursor_details: None,
            stat_generated_at: None,
        }
    }
}


