/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct PersistencePolicies {
    #[serde(rename = "bookkeeperEnsemble", skip_serializing_if = "Option::is_none")]
    pub bookkeeper_ensemble: Option<i32>,
    #[serde(rename = "bookkeeperWriteQuorum", skip_serializing_if = "Option::is_none")]
    pub bookkeeper_write_quorum: Option<i32>,
    #[serde(rename = "bookkeeperAckQuorum", skip_serializing_if = "Option::is_none")]
    pub bookkeeper_ack_quorum: Option<i32>,
    #[serde(rename = "managedLedgerMaxMarkDeleteRate", skip_serializing_if = "Option::is_none")]
    pub managed_ledger_max_mark_delete_rate: Option<f64>,
}

impl PersistencePolicies {
    pub fn new() -> PersistencePolicies {
        PersistencePolicies {
            bookkeeper_ensemble: None,
            bookkeeper_write_quorum: None,
            bookkeeper_ack_quorum: None,
            managed_ledger_max_mark_delete_rate: None,
        }
    }
}


