/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct PersistentTopicInternalStats {
    #[serde(rename = "entriesAddedCounter", skip_serializing_if = "Option::is_none")]
    pub entries_added_counter: Option<i64>,
    #[serde(rename = "numberOfEntries", skip_serializing_if = "Option::is_none")]
    pub number_of_entries: Option<i64>,
    #[serde(rename = "totalSize", skip_serializing_if = "Option::is_none")]
    pub total_size: Option<i64>,
    #[serde(rename = "currentLedgerEntries", skip_serializing_if = "Option::is_none")]
    pub current_ledger_entries: Option<i64>,
    #[serde(rename = "currentLedgerSize", skip_serializing_if = "Option::is_none")]
    pub current_ledger_size: Option<i64>,
    #[serde(rename = "lastLedgerCreatedTimestamp", skip_serializing_if = "Option::is_none")]
    pub last_ledger_created_timestamp: Option<String>,
    #[serde(rename = "lastLedgerCreationFailureTimestamp", skip_serializing_if = "Option::is_none")]
    pub last_ledger_creation_failure_timestamp: Option<String>,
    #[serde(rename = "waitingCursorsCount", skip_serializing_if = "Option::is_none")]
    pub waiting_cursors_count: Option<i32>,
    #[serde(rename = "pendingAddEntriesCount", skip_serializing_if = "Option::is_none")]
    pub pending_add_entries_count: Option<i32>,
    #[serde(rename = "lastConfirmedEntry", skip_serializing_if = "Option::is_none")]
    pub last_confirmed_entry: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "ledgers", skip_serializing_if = "Option::is_none")]
    pub ledgers: Option<Vec<crate::models::LedgerInfo>>,
    #[serde(rename = "cursors", skip_serializing_if = "Option::is_none")]
    pub cursors: Option<::std::collections::HashMap<String, crate::models::CursorStats>>,
}

impl PersistentTopicInternalStats {
    pub fn new() -> PersistentTopicInternalStats {
        PersistentTopicInternalStats {
            entries_added_counter: None,
            number_of_entries: None,
            total_size: None,
            current_ledger_entries: None,
            current_ledger_size: None,
            last_ledger_created_timestamp: None,
            last_ledger_creation_failure_timestamp: None,
            waiting_cursors_count: None,
            pending_add_entries_count: None,
            last_confirmed_entry: None,
            state: None,
            ledgers: None,
            cursors: None,
        }
    }
}


