/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceUsage {
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<f64>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<f64>,
}

impl ResourceUsage {
    pub fn new() -> ResourceUsage {
        ResourceUsage {
            usage: None,
            limit: None,
        }
    }
}


