/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceDescription {
    #[serde(rename = "usagePct", skip_serializing_if = "Option::is_none")]
    pub usage_pct: Option<i32>,
    #[serde(rename = "resourceUsage", skip_serializing_if = "Option::is_none")]
    pub resource_usage: Option<::std::collections::HashMap<String, crate::models::ResourceUsage>>,
}

impl ResourceDescription {
    pub fn new() -> ResourceDescription {
        ResourceDescription {
            usage_pct: None,
            resource_usage: None,
        }
    }
}


