/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct RetentionPolicies {
    #[serde(rename = "retentionTimeInMinutes", skip_serializing_if = "Option::is_none")]
    pub retention_time_in_minutes: Option<i32>,
    #[serde(rename = "retentionSizeInMB", skip_serializing_if = "Option::is_none")]
    pub retention_size_in_mb: Option<i64>,
}

impl RetentionPolicies {
    pub fn new() -> RetentionPolicies {
        RetentionPolicies {
            retention_time_in_minutes: None,
            retention_size_in_mb: None,
        }
    }
}


