/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscribeRate {
    #[serde(rename = "subscribeThrottlingRatePerConsumer", skip_serializing_if = "Option::is_none")]
    pub subscribe_throttling_rate_per_consumer: Option<i32>,
    #[serde(rename = "ratePeriodInSecond", skip_serializing_if = "Option::is_none")]
    pub rate_period_in_second: Option<i32>,
}

impl SubscribeRate {
    pub fn new() -> SubscribeRate {
        SubscribeRate {
            subscribe_throttling_rate_per_consumer: None,
            rate_period_in_second: None,
        }
    }
}


